baseURL = "https://webwhiskyweekend.com/"
languageCode = "en-us"
title = "Web Whisky Weekend"
theme = "webwhiskyweekend"
staticDir = ["static", "data"]

[menu]
    [[menu.nav2]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.nav2]]
        name = "Whisky"
        url = "/the-whisky/"
        weight = 2

    [[menu.nav2]]
        name = "Food"
        url = "/the-food/"
        weight = 3

    [[menu.nav2]]
        name = "People"
        url = "/people/"
        weight = 4

    [[menu.nav2]]
        name = "House"
        url = "/the-house/"
        weight = 5

    [[menu.nav2]]
        name = "Register"
        url = "/register/"
        weight = 6
    